### PR TITLE
node.js-ification

### PR DESCRIPTION
**Pull request by mrose17**
1. fix copyright in LICENSE file
2. update API to be more node.js-like
3. add additional dependencies to package.json
4. move the authorization code into the air conditioner module
5. add a discovery module
6. update air conditioner module and test file to use new API
7. add .gitignore

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
Problem 1:

```
/home/clockwerx/foo/test.js:3
new API().on('discovery', function(aircon) {
^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/clockwerx/foo/test.js:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

```
var API = require('./samsung-airconditioner').API;

```

should probably be

```
var API = require('./samsung-airconditioner')
```

**Comment by mrose17** [comment]
actually, no. back in 5m with a fix.

**Comment by CloCkWeRX** [comment]
Problem two: you don't want to do the token fetching (and physical interaction with your A/C) evey time you want to play with the air conditioner - that's why the authenticator and the driving the aircode code were split (SRP).

I can't tell very easily how you'd inject the existing token looking at the new code - login() doesn't always need to be invoked if you already have the token.

**Comment by mrose17** [comment]
if you look at the login function, you'll see that if you pass a token to it, it won't try to get another one, rather it remembers the value, starts the "real" connection, and returns immediately...

**Comment by mrose17** [comment]
i think it's fixed… grab "the latest" (-;

**Comment by CloCkWeRX** [comment]
Did you mean to close it?  Will test in a bit,  am out right now.

**Comment by mrose17** [comment]
oops… i think it's fixed, but let's leave it open for now!

**Comment by CloCkWeRX** [comment]
So, discovery works

```
clockwerx@clockwerx-laptop:~/foo$ node test.js 
listening
{ interface: 'wlan0', ipaddr: '192.168.1.3', portno: 1900 }
SSDP listening on http://0.0.0.0:1900
multicasting
{ interface: 'wlan0', ipaddr: '192.168.1.255', portno: 1900 }
SSDP response
{ rinfo: { address: '192.168.1.3', family: 'IPv4', port: 1900, size: 189 } }
SSDP response
{ rinfo: 
   { address: '192.168.1.15',
     family: 'IPv4',
     port: 49131,
     size: 355 } }

multicasting
{ interface: 'wlan0', ipaddr: '192.168.1.255', portno: 1900 }
```

... but the .on('discovery') never fires.

**Comment by CloCkWeRX** [comment]
Ah hah>

```
new API().on('discovery', function(aircon) {
```

vs

.emit('discover')

**Comment by mrose17** [comment]
oops. typo. grab it again.

**Comment by mrose17** [comment]
yes, should be 'discover' (events are verbs not nouns);

**Comment by CloCkWeRX** [comment]
After that:
login error: connect ECONNREFUSED

For some reason it wants to connect to my local machine, not the discovered one (192.168.1.15)

```
{ port: 2878, host: '192.168.1.3', rejectUnauthorized: false }
```

We should probably deliberately exclude ourselves from the discovered devices.

Anyway it does eventually discover the aircon and get to the right machine.

```
$ node test.js 
listening
{ interface: 'wlan0', ipaddr: '192.168.1.3', portno: 1900 }
SSDP listening on http://0.0.0.0:1900
multicasting
{ interface: 'wlan0', ipaddr: '192.168.1.255', portno: 1900 }
SSDP response
{ rinfo: { address: '192.168.1.3', family: 'IPv4', port: 1900, size: 189 } }
login error: connect ECONNREFUSED
SSDP response
{ rinfo: 
   { address: '192.168.1.15',
     family: 'IPv4',
     port: 50010,
     size: 355 } }
connected
{ ipaddr: '192.168.1.15', port: 2878, tls: true }
please power on the device within the next 30 seconds
connected
{ ipaddr: '192.168.1.15', port: 2878, tls: true }
please power on the device within the next 30 seconds
connected
{ ipaddr: '192.168.1.15', port: 2878, tls: true }
please power on the device within the next 30 seconds
connected
{ ipaddr: '192.168.1.15', port: 2878, tls: true }
please power on the device within the next 30 seconds
connected
{ ipaddr: '192.168.1.15', port: 2878, tls: true }
please power on the device within the next 30 seconds
multicasting
{ interface: 'wlan0', ipaddr: '192.168.1.255', portno: 1900 }
login error: connect ECONNREFUSED
connected
{ ipaddr: '192.168.1.15', port: 2878, tls: true }
please power on the device within the next 30 seconds
connected
{ ipaddr: '192.168.1.15', port: 2878, tls: true }
please power on the device within the next 30 seconds
connected
{ ipaddr: '192.168.1.15', port: 2878, tls: true }
please power on the device within the next 30 seconds
connected
{ ipaddr: '192.168.1.15', port: 2878, tls: true }
please power on the device within the next 30 seconds
connected
{ ipaddr: '192.168.1.15', port: 2878, tls: true }
please power on the device within the next 30 seconds
multicasting
{ interface: 'wlan0', ipaddr: '192.168.1.255', portno: 1900 }
login error: connect ECONNREFUSED
login error: read ECONNRESET
login error: socket hang up
login error: premature eof
login error: read ECONNRESET
login error: read ECONNRESET
login error: read ECONNRESET
```

Unfortunately, it doesn't go much further - it should only trigger the token fetching _once_ or start blocking (if I'm already connected/discovered, don't double connect)

**Comment by CloCkWeRX** [comment]
So, made it blocking via:

```
var logging_on = {};
new API().on('discover', function(aircon) {
  if (logging_on[aircon.options.ip]) { return; }
  logging_on[aircon.options.ip] = true;
  ... 
}
```

... but it falls over (no token requesting takes place).

I still think you should reintroduce the seperation between "connect for token" and "connect for auth".

SamsungAirconditionerAuthenticator shows you how to request the token

```
    if (line == '<?xml version="1.0" encoding="utf-8" ?><Update Type="InvalidateAccount"/>') {
      return send('<Request Type="GetToken" />');
    }
```

The response to you getToken request (above), which should fire the waiting event (not the fact a number of lines have been read)

```
    if (line == '<?xml version="1.0" encoding="utf-8" ?><Response Type="GetToken" Status="Ready"/>') {
      self.socket.emit('physicallyAuthenticating'); //     console.log('please power on the device within the next 30 seconds');
      return;
```

the typical error if you took too long:

```
    if (line == '<?xml version="1.0" encoding="utf-8" ?><Response Status="Fail" Type="Authenticate" ErrorCode="301" />') {
      self.socket.emit('failedAuthentication');
      return;
    }
```

or success - any line matching Token="....."

```
   var matches = line.match(/Token="(.*)"/)
    if (matches) {
      self.socket.emit('authenticated', matches[1]);
      return;
    }
```

That conversation is different to 90% of the other messages, because you have to go back and forth, as opposed to just pushing out content ("Turn on! Temp 23 degrees C!")

Steal the guts of 

```

  carrier.carry(self.socket, function(line) {
    if (line == 'DRC-1.00')   {
      return;
    }

    if (line == '<?xml version="1.0" encoding="utf-8" ?><Update Type="InvalidateAccount"/>') {
      return send('<Request Type="GetToken" />');
    }

    if (line == '<?xml version="1.0" encoding="utf-8" ?><Response Type="GetToken" Status="Ready"/>') {
      self.socket.emit('physicallyAuthenticating');
      return;
    }

    if (line == '<?xml version="1.0" encoding="utf-8" ?><Response Status="Fail" Type="Authenticate" ErrorCode="301" />') {
      self.socket.emit('failedAuthentication');
      return;
    }

    var matches = line.match(/Token="(.*)"/)
    if (matches) {
      self.socket.emit('authenticated', matches[1]);
      return;
    }

    // console.log(line);
  });
```

and you'll be sorted.

**Comment by mrose17** [comment]
let's try it. go ahead and modify your copy and get it working and then submit a pull request!

**Comment by CloCkWeRX** [comment]
Logs of it working (get token, then login, then on/off)

```
connected
{ ipaddr: '192.168.1.15', port: 2878, tls: true }
read
DRC-1.00
read
<?xml version="1.0" encoding="utf-8" ?><Update Type="InvalidateAccount"/>
read
<?xml version="1.0" encoding="utf-8" ?><Response Type="GetToken" Status="Ready"/>
Please power on the device within the next 30 seconds
read
<?xml version="1.0" encoding="utf-8" ?><Update Type="GetToken" Status="Completed" Token="98854465-6273-M559-N887-373832354144"/>
Token is 98854465-6273-M559-N887-373832354144
multicasting
{ interface: 'wlan0', ipaddr: '192.168.1.255', portno: 1900 }
write
{ line: '<Request Type="DeviceControl"><Control CommandID="cmd4747" DUID="7825AD103D06"><Attr ID="AC_FUN_POWER" Value="On" /></Control></Request>' }
connected
{ ipaddr: '192.168.1.15', port: 2878, tls: true }
write
{ line: '<Request Type="AuthToken"><User Token="98854465-6273-M559-N887-373832354144" /></Request>' }
read
{ line: '<?xml version="1.0" encoding="utf-8" ?><Response Type="AuthToken" Status="Okay" StartFrom="1970-01-01/09:55:29"/>' }
write
{ line: '<Request Type="DeviceControl"><Control CommandID="cmd6754" DUID="7825AD103D06"><Attr ID="AC_FUN_POWER" Value="Off" /></Control></Request>' }
read
{ line: '<?xml version="1.0" encoding="utf-8" ?><Response Type="DeviceControl" Status="Okay" DUID="7825AD103D06" CommandID="cmd6754"/>' }
read
{ line: '<?xml version="1.0" encoding="utf-8" ?><Update Type="Status"><Status DUID="7825AD103D060000" GroupID="AC" ModelID="AC"><Attr ID="AC_FUN_POWER" Value="Off" /></Status></Update>' }

```

**Comment by CloCkWeRX** [comment]
I should really knock up a testing fake at some point, so that I don't have to interact with the physical machine/you can self test.

**Comment by mrose17** [comment]
that would be great! if you have questions on node.js let me know. i was hoping that i wasn't messing up the state machine with the authentication stuff, but with no way to test…

good luck!

**Pull request merged**
